// Word list: ~300 words for reading practice
// All words are 6 letters or fewer with phonetically regular sounds
// LIMITED TO: concrete nouns and clear physical actions with obvious visual representations

export interface Word {
  word: string;
  emoji: string;
  letters: ('b' | 'd' | 'p')[]; // which target letters this word contains (empty = no b/d/p)
}

export const wordList: Word[] = [
  // ============================================
  // WORDS WITHOUT B, D, OR P (general practice)
  // ============================================

  // === ANIMALS (no b/d/p) ===
  { word: "cat", emoji: "🐱", letters: [] },
  { word: "cow", emoji: "🐄", letters: [] },
  { word: "fish", emoji: "🐟", letters: [] },
  { word: "frog", emoji: "🐸", letters: [] },
  { word: "fox", emoji: "🦊", letters: [] },
  { word: "hen", emoji: "🐔", letters: [] },
  { word: "lion", emoji: "🦁", letters: [] },
  { word: "owl", emoji: "🦉", letters: [] },
  { word: "rat", emoji: "🐀", letters: [] },
  { word: "shark", emoji: "🦈", letters: [] },
  { word: "swan", emoji: "🦢", letters: [] },
  { word: "tiger", emoji: "🐯", letters: [] },
  { word: "whale", emoji: "🐋", letters: [] },
  { word: "wolf", emoji: "🐺", letters: [] },
  { word: "ant", emoji: "🐜", letters: [] },
  { word: "goat", emoji: "🐐", letters: [] },
  { word: "snail", emoji: "🐌", letters: [] },
  { word: "worm", emoji: "🪱", letters: [] },
  { word: "goose", emoji: "🪿", letters: [] },
  { word: "mouse", emoji: "🐭", letters: [] },
  { word: "horse", emoji: "🐴", letters: [] },
  { word: "turtle", emoji: "🐢", letters: [] },
  { word: "camel", emoji: "🐪", letters: [] },
  { word: "koala", emoji: "🐨", letters: [] },
  { word: "sloth", emoji: "🦥", letters: [] },
  { word: "otter", emoji: "🦦", letters: [] },
  { word: "skunk", emoji: "🦨", letters: [] },
  { word: "llama", emoji: "🦙", letters: [] },
  { word: "seal", emoji: "🦭", letters: [] },
  { word: "chick", emoji: "🐤", letters: [] },

  // === FOOD (no b/d/p) ===
  { word: "corn", emoji: "🌽", letters: [] },
  { word: "egg", emoji: "🥚", letters: [] },
  { word: "kiwi", emoji: "🥝", letters: [] },
  { word: "lemon", emoji: "🍋", letters: [] },
  { word: "lime", emoji: "🍋", letters: [] },
  { word: "mango", emoji: "🥭", letters: [] },
  { word: "melon", emoji: "🍈", letters: [] },
  { word: "milk", emoji: "🥛", letters: [] },
  { word: "nut", emoji: "🥜", letters: [] },
  { word: "orange", emoji: "🍊", letters: [] },
  { word: "rice", emoji: "🍚", letters: [] },
  { word: "salt", emoji: "🧂", letters: [] },
  { word: "tea", emoji: "🍵", letters: [] },
  { word: "taco", emoji: "🌮", letters: [] },
  { word: "cake", emoji: "🎂", letters: [] },
  { word: "ice", emoji: "🧊", letters: [] },
  { word: "meat", emoji: "🥩", letters: [] },
  { word: "cherry", emoji: "🍒", letters: [] },
  { word: "honey", emoji: "🍯", letters: [] },
  { word: "juice", emoji: "🧃", letters: [] },
  { word: "olive", emoji: "🫒", letters: [] },
  { word: "cheese", emoji: "🧀", letters: [] },
  { word: "onion", emoji: "🧅", letters: [] },
  { word: "garlic", emoji: "🧄", letters: [] },
  { word: "carrot", emoji: "🥕", letters: [] },

  // === HOUSEHOLD (no b/d/p) ===
  { word: "chair", emoji: "🪑", letters: [] },
  { word: "couch", emoji: "🛋️", letters: [] },
  { word: "fork", emoji: "🍴", letters: [] },
  { word: "glass", emoji: "🥃", letters: [] },
  { word: "hat", emoji: "🎩", letters: [] },
  { word: "key", emoji: "🔑", letters: [] },
  { word: "vase", emoji: "🏺", letters: [] },
  { word: "watch", emoji: "⌚", letters: [] },
  { word: "fan", emoji: "🪭", letters: [] },
  { word: "sock", emoji: "🧦", letters: [] },
  { word: "coat", emoji: "🧥", letters: [] },
  { word: "shirt", emoji: "👕", letters: [] },
  { word: "shoe", emoji: "👟", letters: [] },
  { word: "ring", emoji: "💍", letters: [] },
  { word: "crown", emoji: "👑", letters: [] },
  { word: "mask", emoji: "🎭", letters: [] },
  { word: "saw", emoji: "🪚", letters: [] },
  { word: "axe", emoji: "🪓", letters: [] },
  { word: "hammer", emoji: "🔨", letters: [] },
  { word: "light", emoji: "💡", letters: [] },
  { word: "mirror", emoji: "🪞", letters: [] },
  { word: "yarn", emoji: "🧶", letters: [] },
  { word: "knife", emoji: "🔪", letters: [] },
  { word: "kite", emoji: "🪁", letters: [] },
  { word: "gift", emoji: "🎁", letters: [] },

  // === NATURE (no b/d/p) ===
  { word: "sun", emoji: "☀️", letters: [] },
  { word: "moon", emoji: "🌙", letters: [] },
  { word: "star", emoji: "⭐", letters: [] },
  { word: "tree", emoji: "🌳", letters: [] },
  { word: "leaf", emoji: "🍃", letters: [] },
  { word: "rain", emoji: "🌧️", letters: [] },
  { word: "snow", emoji: "❄️", letters: [] },
  { word: "fire", emoji: "🔥", letters: [] },
  { word: "rock", emoji: "🪨", letters: [] },
  { word: "flower", emoji: "🌸", letters: [] },
  { word: "rose", emoji: "🌹", letters: [] },
  { word: "fog", emoji: "🌫️", letters: [] },
  { word: "storm", emoji: "⛈️", letters: [] },
  { word: "wave", emoji: "🌊", letters: [] },
  { word: "forest", emoji: "🌲", letters: [] },
  { word: "sea", emoji: "🌊", letters: [] },
  { word: "stone", emoji: "🪨", letters: [] },
  { word: "vine", emoji: "🍇", letters: [] },
  { word: "water", emoji: "💧", letters: [] },
  { word: "acorn", emoji: "🌰", letters: [] },

  // === VEHICLES (no b/d/p) ===
  { word: "car", emoji: "🚗", letters: [] },
  { word: "jet", emoji: "✈️", letters: [] },
  { word: "train", emoji: "🚂", letters: [] },
  { word: "truck", emoji: "🚚", letters: [] },
  { word: "van", emoji: "🚐", letters: [] },
  { word: "cart", emoji: "🛒", letters: [] },
  { word: "tram", emoji: "🚃", letters: [] },
  { word: "canoe", emoji: "🛶", letters: [] },
  { word: "taxi", emoji: "🚕", letters: [] },
  { word: "rocket", emoji: "🚀", letters: [] },

  // === ACTIONS (no b/d/p) ===
  { word: "run", emoji: "🏃", letters: [] },
  { word: "sit", emoji: "🧘", letters: [] },
  { word: "swim", emoji: "🏊", letters: [] },
  { word: "walk", emoji: "🚶", letters: [] },
  { word: "eat", emoji: "🍽️", letters: [] },
  { word: "cry", emoji: "😢", letters: [] },
  { word: "fly", emoji: "✈️", letters: [] },
  { word: "hug", emoji: "🤗", letters: [] },
  { word: "kick", emoji: "⚽", letters: [] },
  { word: "kiss", emoji: "💋", letters: [] },
  { word: "sing", emoji: "🎤", letters: [] },
  { word: "cook", emoji: "👨‍🍳", letters: [] },
  { word: "grow", emoji: "🌱", letters: [] },
  { word: "fall", emoji: "🍂", letters: [] },
  { word: "win", emoji: "🏆", letters: [] },
  { word: "cut", emoji: "✂️", letters: [] },
  { word: "row", emoji: "🚣", letters: [] },
  { word: "ski", emoji: "⛷️", letters: [] },
  { word: "wash", emoji: "🧼", letters: [] },
  { word: "wink", emoji: "😉", letters: [] },
  { word: "yawn", emoji: "🥱", letters: [] },
  { word: "grin", emoji: "😁", letters: [] },
  { word: "hear", emoji: "👂", letters: [] },
  { word: "hike", emoji: "🥾", letters: [] },
  { word: "lick", emoji: "👅", letters: [] },
  { word: "lift", emoji: "🏋️", letters: [] },
  { word: "look", emoji: "👀", letters: [] },
  { word: "melt", emoji: "🫠", letters: [] },
  { word: "rest", emoji: "😴", letters: [] },
  { word: "roar", emoji: "🦁", letters: [] },

  // === PEOPLE (no b/d/p) ===
  { word: "man", emoji: "👨", letters: [] },
  { word: "girl", emoji: "👧", letters: [] },
  { word: "mom", emoji: "👩", letters: [] },
  { word: "king", emoji: "👑", letters: [] },
  { word: "queen", emoji: "👸", letters: [] },

  // === MISC (no b/d/p) ===
  { word: "gem", emoji: "💎", letters: [] },
  { word: "song", emoji: "🎵", letters: [] },
  { word: "time", emoji: "⏰", letters: [] },
  { word: "tool", emoji: "🔧", letters: [] },
  { word: "six", emoji: "6️⃣", letters: [] },

  // ============================================
  // WORDS WITH B, D, OR P (confusing letters)
  // ============================================

  // === ANIMALS ===
  { word: "bat", emoji: "🦇", letters: ['b'] },
  { word: "bird", emoji: "🐦", letters: ['b', 'd'] },
  { word: "bear", emoji: "🐻", letters: ['b'] },
  { word: "bee", emoji: "🐝", letters: ['b'] },
  { word: "bug", emoji: "🐛", letters: ['b'] },
  { word: "bunny", emoji: "🐰", letters: ['b'] },
  { word: "dog", emoji: "🐕", letters: ['d'] },
  { word: "duck", emoji: "🦆", letters: ['d'] },
  { word: "deer", emoji: "🦌", letters: ['d'] },
  { word: "pig", emoji: "🐷", letters: ['p'] },
  { word: "pup", emoji: "🐶", letters: ['p'] },
  { word: "pony", emoji: "🐴", letters: ['p'] },
  { word: "cub", emoji: "🐻", letters: ['b'] },
  { word: "crab", emoji: "🦀", letters: ['b'] },
  { word: "zebra", emoji: "🦓", letters: ['b'] },
  { word: "hippo", emoji: "🦛", letters: ['p'] },
  { word: "puppy", emoji: "🐶", letters: ['p'] },
  { word: "rabbit", emoji: "🐰", letters: ['b'] },
  { word: "spider", emoji: "🕷️", letters: ['p', 'd'] },
  { word: "panda", emoji: "🐼", letters: ['p', 'd'] },
  { word: "toad", emoji: "🐸", letters: ['d'] },
  { word: "bird", emoji: "🐦", letters: ['b', 'd'] },
  { word: "lamb", emoji: "🐑", letters: ['b'] },
  { word: "cod", emoji: "🐟", letters: ['d'] },

  // === FOOD & DRINKS ===
  { word: "bread", emoji: "🍞", letters: ['b', 'd'] },
  { word: "pie", emoji: "🥧", letters: ['p'] },
  { word: "pear", emoji: "🍐", letters: ['p'] },
  { word: "peach", emoji: "🍑", letters: ['p'] },
  { word: "peas", emoji: "🫛", letters: ['p'] },
  { word: "pepper", emoji: "🫑", letters: ['p'] },
  { word: "pickle", emoji: "🥒", letters: ['p'] },
  { word: "pizza", emoji: "🍕", letters: ['p'] },
  { word: "plum", emoji: "🫐", letters: ['p'] },
  { word: "potato", emoji: "🥔", letters: ['p'] },
  { word: "donut", emoji: "🍩", letters: ['d'] },
  { word: "apple", emoji: "🍎", letters: ['p'] },
  { word: "banana", emoji: "🍌", letters: ['b'] },
  { word: "beans", emoji: "🫘", letters: ['b'] },
  { word: "butter", emoji: "🧈", letters: ['b'] },
  { word: "candy", emoji: "🍬", letters: ['d'] },
  { word: "salad", emoji: "🥗", letters: ['d'] },
  { word: "cup", emoji: "🥤", letters: ['p'] },
  { word: "bowl", emoji: "🥣", letters: ['b'] },
  { word: "bottle", emoji: "🍼", letters: ['b'] },
  { word: "pod", emoji: "🫛", letters: ['p', 'd'] },
  { word: "bun", emoji: "🍔", letters: ['b'] },
  { word: "dip", emoji: "🫕", letters: ['d', 'p'] },
  { word: "pop", emoji: "🥤", letters: ['p'] },

  // === BODY PARTS ===
  { word: "body", emoji: "🧍", letters: ['b', 'd'] },
  { word: "bone", emoji: "🦴", letters: ['b'] },
  { word: "elbow", emoji: "💪", letters: ['b'] },
  { word: "hand", emoji: "✋", letters: ['d'] },
  { word: "head", emoji: "👤", letters: ['d'] },
  { word: "lip", emoji: "👄", letters: ['p'] },
  { word: "paw", emoji: "🐾", letters: ['p'] },

  // === HOUSEHOLD ITEMS ===
  { word: "bed", emoji: "🛏️", letters: ['b', 'd'] },
  { word: "bell", emoji: "🔔", letters: ['b'] },
  { word: "book", emoji: "📖", letters: ['b'] },
  { word: "box", emoji: "📦", letters: ['b'] },
  { word: "broom", emoji: "🧹", letters: ['b'] },
  { word: "brush", emoji: "🖌️", letters: ['b'] },
  { word: "bucket", emoji: "🪣", letters: ['b'] },
  { word: "button", emoji: "🔘", letters: ['b'] },
  { word: "door", emoji: "🚪", letters: ['d'] },
  { word: "desk", emoji: "🪑", letters: ['d'] },
  { word: "dish", emoji: "🍽️", letters: ['d'] },
  { word: "doll", emoji: "🧸", letters: ['d'] },
  { word: "drum", emoji: "🥁", letters: ['d'] },
  { word: "pen", emoji: "🖊️", letters: ['p'] },
  { word: "pot", emoji: "🍲", letters: ['p'] },
  { word: "pan", emoji: "🍳", letters: ['p'] },
  { word: "pin", emoji: "📌", letters: ['p'] },
  { word: "pencil", emoji: "✏️", letters: ['p'] },
  { word: "pillow", emoji: "🛋️", letters: ['p'] },
  { word: "plate", emoji: "🍽️", letters: ['p'] },
  { word: "tub", emoji: "🛁", letters: ['b'] },
  { word: "web", emoji: "🕸️", letters: ['b'] },
  { word: "globe", emoji: "🌍", letters: ['b'] },
  { word: "lamp", emoji: "💡", letters: ['p'] },
  { word: "mop", emoji: "🧹", letters: ['p'] },
  { word: "ladder", emoji: "🪜", letters: ['d'] },
  { word: "window", emoji: "🪟", letters: ['d'] },
  { word: "basket", emoji: "🧺", letters: ['b'] },
  { word: "ribbon", emoji: "🎀", letters: ['b'] },
  { word: "candle", emoji: "🕯️", letters: ['d'] },
  { word: "puzzle", emoji: "🧩", letters: ['p'] },
  { word: "puppet", emoji: "🧸", letters: ['p'] },
  { word: "pad", emoji: "📝", letters: ['p', 'd'] },
  { word: "lid", emoji: "🫙", letters: ['d'] },
  { word: "knob", emoji: "🚪", letters: ['b'] },
  { word: "crib", emoji: "🛒", letters: ['b'] },

  // === CLOTHING & ACCESSORIES ===
  { word: "belt", emoji: "👔", letters: ['b'] },
  { word: "boot", emoji: "🥾", letters: ['b'] },
  { word: "cap", emoji: "🧢", letters: ['p'] },
  { word: "bag", emoji: "👜", letters: ['b'] },
  { word: "dress", emoji: "👗", letters: ['d'] },
  { word: "pocket", emoji: "👖", letters: ['p'] },
  { word: "purse", emoji: "👛", letters: ['p'] },
  { word: "bib", emoji: "🍼", letters: ['b'] },

  // === VEHICLES & TRANSPORTATION ===
  { word: "bike", emoji: "🚲", letters: ['b'] },
  { word: "boat", emoji: "⛵", letters: ['b'] },
  { word: "bus", emoji: "🚌", letters: ['b'] },
  { word: "ship", emoji: "🚢", letters: ['p'] },
  { word: "plane", emoji: "✈️", letters: ['p'] },
  { word: "sled", emoji: "🛷", letters: ['d'] },
  { word: "pedal", emoji: "🚲", letters: ['p', 'd'] },

  // === BUILDINGS & PLACES ===
  { word: "barn", emoji: "🏚️", letters: ['b'] },
  { word: "cabin", emoji: "🏠", letters: ['b'] },
  { word: "pond", emoji: "🏞️", letters: ['p', 'd'] },
  { word: "pool", emoji: "🏊", letters: ['p'] },
  { word: "park", emoji: "🏞️", letters: ['p'] },
  { word: "beach", emoji: "🏖️", letters: ['b'] },
  { word: "bridge", emoji: "🌉", letters: ['b', 'd'] },
  { word: "shop", emoji: "🏪", letters: ['p'] },
  { word: "den", emoji: "🏠", letters: ['d'] },
  { word: "road", emoji: "🛣️", letters: ['d'] },

  // === NATURE ===
  { word: "plant", emoji: "🌱", letters: ['p'] },
  { word: "bud", emoji: "🌱", letters: ['b', 'd'] },
  { word: "mud", emoji: "🟤", letters: ['d'] },
  { word: "sand", emoji: "🏖️", letters: ['d'] },
  { word: "cloud", emoji: "☁️", letters: ['d'] },
  { word: "puddle", emoji: "💧", letters: ['p', 'd'] },
  { word: "pebble", emoji: "🪨", letters: ['p', 'b'] },

  // === TOYS & FUN ===
  { word: "ball", emoji: "⚽", letters: ['b'] },
  { word: "dice", emoji: "🎲", letters: ['d'] },
  { word: "block", emoji: "🧱", letters: ['b'] },
  { word: "bubble", emoji: "🫧", letters: ['b'] },
  { word: "top", emoji: "🪀", letters: ['p'] },
  { word: "bat", emoji: "🏏", letters: ['b'] },

  // === PEOPLE ===
  { word: "baby", emoji: "👶", letters: ['b'] },
  { word: "boy", emoji: "👦", letters: ['b'] },
  { word: "dad", emoji: "👨", letters: ['d'] },
  { word: "kid", emoji: "🧒", letters: ['d'] },
  { word: "buddy", emoji: "🤝", letters: ['b', 'd'] },
  { word: "pirate", emoji: "🏴‍☠️", letters: ['p'] },

  // === TOOLS & OBJECTS ===
  { word: "brick", emoji: "🧱", letters: ['b'] },
  { word: "map", emoji: "🗺️", letters: ['p'] },
  { word: "trap", emoji: "🪤", letters: ['p'] },
  { word: "rope", emoji: "🪢", letters: ['p'] },
  { word: "laptop", emoji: "💻", letters: ['p'] },
  { word: "robot", emoji: "🤖", letters: ['b'] },

  // === ACTIONS (clear physical actions) ===
  { word: "dig", emoji: "⛏️", letters: ['d'] },
  { word: "hop", emoji: "🐰", letters: ['p'] },
  { word: "clap", emoji: "👏", letters: ['p'] },
  { word: "drop", emoji: "💧", letters: ['d', 'p'] },
  { word: "drip", emoji: "💧", letters: ['d', 'p'] },
  { word: "step", emoji: "👣", letters: ['p'] },
  { word: "skip", emoji: "🏃", letters: ['p'] },
  { word: "nap", emoji: "😴", letters: ['p'] },
  { word: "dive", emoji: "🏊", letters: ['d'] },
  { word: "drink", emoji: "🥤", letters: ['d'] },
  { word: "bend", emoji: "🤸", letters: ['b', 'd'] },
  { word: "bump", emoji: "🤕", letters: ['b', 'p'] },
  { word: "paddle", emoji: "🛶", letters: ['p', 'd'] },

  // === SPACE & MISC ===
  { word: "planet", emoji: "🪐", letters: ['p'] },
  { word: "dragon", emoji: "🐉", letters: ['d'] },
  { word: "pumpkin", emoji: "🎃", letters: ['p'] },
  { word: "prize", emoji: "🏆", letters: ['p'] },
  { word: "stamp", emoji: "📮", letters: ['p'] },
  { word: "penny", emoji: "🪙", letters: ['p'] },
  { word: "dime", emoji: "🪙", letters: ['d'] },
  { word: "band", emoji: "🎸", letters: ['b', 'd'] },
  { word: "tent", emoji: "⛺", letters: [] },
  { word: "sponge", emoji: "🧽", letters: ['p'] },
];

// Function to get random words for a game session
export function getRandomWords(count: number, bdpOnly?: boolean): Word[] {
  let filtered = wordList;

  if (bdpOnly) {
    // Only include words that contain b, d, or p
    filtered = wordList.filter(w => w.letters.length > 0);
  }

  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
